"""add mit_task_id to daily_stats

Revision ID: 0f70781fb706
Revises: 85be95c9b234
Create Date: 2026-03-10 18:28:15.815130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f70781fb706'
down_revision: Union[str, Sequence[str], None] = '85be95c9b234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_stats', sa.Column('mit_task_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_daily_stats_mit_task_id', 'daily_stats', 'tasks', ['mit_task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_daily_stats_mit_task_id', 'daily_stats', type_='foreignkey')
    op.drop_column('daily_stats', 'mit_task_id')
    # ### end Alembic commands ###
